baseURL = 'https://tourmaline-clafoutis-8f53da.netlify.app'
languageCode = 'en-us'
title = 'Microsite Testing'
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      table = true
    [markup.goldmark.renderer]
      unsafe = true
