site_url: https://tourmaline-clafoutis-8f53da.netlify.app

backend:
  name: git-gateway

media_library:
  name: uploadcare
  config:
    publicKey: 7b24509310ddb9c7d9fb
  settings:
    autoFilename: true
    defaultOperations: '/resize/800x600/'

collections:
  - name: 'guide'
    label: 'Guide'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    folder: 'content/guides'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'guide' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Cover Image', name: 'cover_image', widget: 'image' }
      - label: 'Sections'
        name: 'sections'
        widget: 'list'
        fields:
          - { label: 'Heading', name: 'heading', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown', required: false }
          - label: 'Image Steps'
            name: 'image_steps'
            widget: 'list'
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Paragraph', name: 'paragraph', widget: 'text', required: false }
